"""
Django settings for mainApp project.

Generated by 'django-admin startproject' using Django 5.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from djongo.base import DatabaseWrapper
from djongo.operations import DatabaseOperations

class PatchedDatabaseOperations(DatabaseOperations):

    def conditional_expression_supported_in_where_clause(self, expression):
        return False


DatabaseWrapper.ops_class = PatchedDatabaseOperations






from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-q1c+djzfkpz=t+x=(gvr0m#&qaa_nw=^xd&d0k@u%4n$112=zf'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'command',
    'cart',
    'book',
    'clothes',
    'mobiles',
    'category',
    'user',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mainApp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mainApp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'djongo',
        'NAME': 'hhhhhhhh',
        'CONN_MAX_AGE': 600,
    },
    # 'admins_db': {
    #     'ENGINE': 'djongo',
    #     'NAME': 'admins',
    #     'CONN_MAX_AGE': 600,
    # },
    'user_db': {
        'ENGINE': 'djongo',
        'NAME': 'user',
        'CONN_MAX_AGE': 600,
    },
    'book_db': {
        'ENGINE': 'djongo',
        'NAME': 'book',
        'CONN_MAX_AGE': 600,
    },
    'clothes_db': {
        'ENGINE': 'djongo',
        'NAME': 'clothes',
        'CONN_MAX_AGE': 600,
    },
    'mobiles_db': {
        'ENGINE': 'djongo',
        'NAME': 'mobiles',
        'CONN_MAX_AGE': 600,
    },
    'category_db': {
        'ENGINE': 'djongo',
        'NAME': 'category',
        'CONN_MAX_AGE': 600,
    },
    'cart_db': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'cart',
        'USER': 'root',
        'PASSWORD': '27082002',
        'HOST': 'localhost',
        'PORT': '3306'
    },
}

DATABASE_ROUTERS = [
    'mainApp.router.AuthRouter',
    'mainApp.router.Book',
    'mainApp.router.Clothes',
    'mainApp.router.Mobiles',
    'mainApp.router.Cart',
    'mainApp.router.User',
    'mainApp.router.Category',

    
]


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
